# Generated by Django 6.0.3 on 2026-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_teacher_address_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
