# Generated by Django 6.0.3 on 2026-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
