# Generated by Django 6.0.3 on 2026-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_exam_description_exam_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
