# Generated by Django 6.0.3 on 2026-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
