# Generated by Django 6.0.3 on 2026-03-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_class_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'department')},
        ),
    ]
