# Generated by Django 6.0.3 on 2026-03-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectproposal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
            preserve_default=False,
        ),
    ]
