# Generated by Django 6.0.3 on 2026-03-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
    ]
