# Generated by Django 6.0.3 on 2026-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetableproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableproposal',
            name='status',
        ),
        migrations.AlterField(
            model_name='timetableproposal',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
