# Generated by Django 6.0.3 on 2026-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetableproposal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
