# Generated by Django 6.0.3 on 2026-03-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetable_class_name_timetable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='student_class',
            field=models.CharField(default='class1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
