# Generated by Django 6.0.3 on 2026-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_timetable_class_name_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
