# Generated by Django 6.0.3 on 2026-03-30 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_class'),
        ('timetable', '0009_alter_timetable_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
    ]
