# Generated by Django 6.0.3 on 2026-03-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_class_section'),
        ('timetable', '0010_alter_timetable_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableproposal',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
    ]
