# Generated by Django 6.0.3 on 2026-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('class A', 'class A'), ('class B', 'class B'), ('class C', 'class C')], max_length=50),
        ),
    ]
