# Generated by Django 6.0.3 on 2026-03-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
