# Generated by Django 6.0.3 on 2026-03-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_class_section'),
        ('student', '0010_alter_student_student_class_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
            preserve_default=False,
        ),
    ]
